apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/C/k8s/storage/nexus-pv"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        runAsUser: 200
        runAsGroup: 200
        fsGroup: 200
      containers:
        - name: nexus
          image: aliz/nexus3:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: nexus-storage
              mountPath: /nexus-data
            - name: google-key
              mountPath: /etc/google-secret
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/google-secret/key.json
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 10

      volumes:
        - name: nexus-storage
          persistentVolumeClaim:
            claimName: nexus-pvc
        - name: google-key
          secret:
            secretName: google-store
            items:
              - key: service_account_key
                path: key.json

---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  selector:
    app: nexus
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort


